default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>

development:
  <<: *default
  database: <%= ENV["CI"] ? "good_job_test" : "good_job_development" %>

test:
  <<: *default
  database: good_job_test
  reaping_frequency: 0

production:
  <<: *default
  database: <%= ENV["CI"] ? "good_job_test" : "good_job_development" %>

demo:
  <<: *default
  database: "good_job_demo"
  url: <%= ENV['DATABASE_URL'] %>
